name = "rabyte-tech"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "rabyte_d1"
database_id = "4901e8f2-89da-41b4-b841-893d18e9a4f4"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "rabyte-store-assets"

[[kv_namespaces]]
binding = "KV"
id = "d77e4aec3bc34a148a853a3d7c9097af"
